# Generated by Django 4.2.5 on 2023-10-20 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('flag_img', models.ImageField(upload_to='flags_images/')),
                ('flag_path', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Ticker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker_name', models.CharField(max_length=200)),
                ('full_name', models.CharField(max_length=255)),
                ('origin_country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='getstocksapp.country')),
            ],
        ),
    ]
