# Generated by Django 4.2.5 on 2023-10-22 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getstocksapp', '0002_remove_country_flag_path_alter_country_flag_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticker',
            name='full_name',
        ),
        migrations.AddField(
            model_name='ticker',
            name='address',
            field=models.CharField(default='No data', max_length=255),
        ),
        migrations.AddField(
            model_name='ticker',
            name='company_description',
            field=models.CharField(default='No data', max_length=255),
        ),
        migrations.AddField(
            model_name='ticker',
            name='company_name',
            field=models.CharField(default='No data', max_length=255),
        ),
        migrations.AddField(
            model_name='ticker',
            name='currency',
            field=models.CharField(default='No data', max_length=255),
        ),
        migrations.AddField(
            model_name='ticker',
            name='data_fetched',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ticker',
            name='exchange',
            field=models.CharField(default='No data', max_length=255),
        ),
        migrations.AddField(
            model_name='ticker',
            name='industry',
            field=models.CharField(default='No data', max_length=255),
        ),
        migrations.AddField(
            model_name='ticker',
            name='sector',
            field=models.CharField(default='No data', max_length=255),
        ),
    ]
