# Generated by Django 4.2.5 on 2023-10-25 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('getstocksapp', '0003_remove_ticker_full_name_ticker_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('logo_img', models.CharField(default='BLANKFLAG.png', max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='ticker',
            name='origin_country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='getstocksapp.market'),
        ),
        migrations.DeleteModel(
            name='Country',
        ),
    ]
