# Generated by Django 4.2.5 on 2023-10-25 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('getstocksapp', '0004_market_alter_ticker_origin_country_delete_country'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticker',
            old_name='origin_country',
            new_name='origin_market',
        ),
    ]
