# Generated by Django 4.2.5 on 2023-11-02 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getstocksapp', '0005_rename_origin_country_ticker_origin_market'),
    ]

    operations = [
        migrations.AddField(
            model_name='market',
            name='logo_path',
            field=models.CharField(default='BLANKFLAG.png', max_length=200),
        ),
        migrations.AlterField(
            model_name='market',
            name='logo_img',
            field=models.ImageField(blank=True, null=True, upload_to='market_logos/'),
        ),
    ]
