# Generated by Django 4.2.5 on 2023-11-04 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getstocksapp', '0006_market_logo_path_alter_market_logo_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticker',
            name='capitalization',
            field=models.BigIntegerField(default=0),
        ),
    ]
