# Generated by Django 4.2.5 on 2023-11-06 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getstocksapp', '0008_remove_market_logo_path_market_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='market',
            name='website',
            field=models.URLField(default='#'),
        ),
    ]
