# Generated by Django 4.2.5 on 2023-12-29 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('getstocksapp', '0014_ticker_temp_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticker',
            name='company_description',
        ),
    ]
