# Generated by Django 4.2.5 on 2023-12-29 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getstocksapp', '0015_remove_ticker_company_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticker',
            name='company_description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
