# Generated by Django 4.2.5 on 2023-12-29 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('getstocksapp', '0016_ticker_company_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticker',
            name='temp_description',
        ),
    ]
