# Generated by Django 5.0.1 on 2024-01-18 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getstocksapp', '0018_wallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='name',
            field=models.CharField(default='anonymous_wallet', max_length=200),
        ),
    ]
