# Generated by Django 5.0.1 on 2024-01-19 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('getstocksapp', '0021_alter_wallet_guests'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallet',
            name='guests',
        ),
    ]
