# Generated by Django 5.0.1 on 2024-01-20 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getstocksapp', '0022_remove_wallet_guests'),
    ]

    operations = [
        migrations.CreateModel(
            name='WalletRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('ticker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='getstocksapp.ticker')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='getstocksapp.wallet')),
            ],
        ),
    ]
