# Generated by Django 5.0.1 on 2024-01-21 22:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getstocksapp', '0023_walletrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='walletrecord',
            name='createation_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
