# Generated by Django 5.0.1 on 2024-01-21 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getstocksapp', '0024_walletrecord_createation_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='walletrecord',
            name='innit_price',
            field=models.FloatField(default=0.0),
        ),
    ]
