# Generated by Django 5.0.1 on 2024-01-21 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('getstocksapp', '0025_walletrecord_innit_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='walletrecord',
            old_name='innit_price',
            new_name='init_price',
        ),
    ]
