# Generated by Django 5.0.1 on 2024-01-23 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('getstocksapp', '0026_rename_innit_price_walletrecord_init_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='walletrecord',
            old_name='createation_time',
            new_name='creation_time',
        ),
    ]
