# Generated by Django 5.0.1 on 2024-01-24 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getstocksapp', '0027_rename_createation_time_walletrecord_creation_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='walletrecord',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
