# Generated by Django 5.0.1 on 2024-03-07 18:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getstocksapp', '0029_wallet_guests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticker',
            name='origin_market',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='market', to='getstocksapp.market'),
        ),
    ]
