# Generated by Django 5.0.1 on 2024-03-07 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getstocksapp', '0030_alter_ticker_origin_market'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticker',
            name='origin_market',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickers', to='getstocksapp.market'),
        ),
    ]
