# Generated by Django 5.0.1 on 2024-04-15 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getstocksapp', '0033_alter_wallet_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Unknown', max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='advisors_images/')),
                ('description', models.TextField(blank=True, default='')),
                ('code', models.TextField(blank=True, default='')),
            ],
        ),
    ]
