# Generated by Django 5.0.1 on 2024-04-26 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getstocksapp', '0034_advisor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advisor',
            name='code',
        ),
        migrations.AddField(
            model_name='advisor',
            name='dictionary_name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
